# dod.ps1 -- interactive Definition-of-Done scaffolder.
# Walks you through the five prompts and writes DEFINITION_OF_DONE.md.

$root = if ($PSScriptRoot) { (Resolve-Path "$PSScriptRoot\..").Path } else { (Get-Location).Path }
$target = Join-Path $root 'DEFINITION_OF_DONE.md'

$user    = Read-Host "USER (who runs the project?)"
$runs    = Read-Host "RUNS (literal command)"
$obs     = Read-Host "OBSERVES (what do they see/hear/feel?)"
$inTime  = Read-Host "IN (time bound, e.g. 'under 5 seconds')"
$constr  = Read-Host "WITH THESE CONSTRAINTS (stack, env, etc.)"

$content = @"
# Definition of Done

**DoD:** User runs ``$runs`` and observes ``$obs`` $inTime.

## Template

```text
USER: $user
RUNS: $runs
OBSERVES: $obs
IN: $inTime
WITH: $constr
```

## Generated by scripts/dod.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
"@
Set-Content -LiteralPath $target -Value $content -Encoding UTF8
Write-Host "Wrote $target"
Write-Host "Open it and tighten the one-sentence DoD at the top."